# Generated by Django 5.0 on 2023-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_year', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newyeararticle',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
