# Generated by Django 5.0 on 2023-12-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_year', '0002_newyeararticle_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newyeararticle',
            name='qr_image',
        ),
    ]
